// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"hud","status":true,"description":"HUD sederhana menampilkan Utang dan Saldo di layar map.","parameters":{"varUtang":"2","varSaldo":"1","varObjektif":"10","switchAktif":"1"}},
{"name":"bukanhud","status":false,"description":"Suara \"blip\" tiap karakter teks muncul (gaya Undertale).","parameters":{"seName":"Cursor2","volume":"40","pitchMin":"90","pitchMax":"115","charSkip":"1"}}
];
